apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: namespace
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 2002
    workingDir: /data
    volumeMounts:
      - mountPath: /data
        name: pvc-pv-id
  volumes:
    - name: pvc-pv-id
      hostPath:
        path: /
